# Generated by Django 4.1.2 on 2023-10-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
