# Generated by Django 4.1.2 on 2023-10-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0003_rename_video_file_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
    ]
