# Generated by Django 4.1.2 on 2023-10-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0005_alter_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_file', models.FileField(upload_to='output/plate/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crime_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='FaceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_file', models.FileField(upload_to='output/face/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crime_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhanced_file', models.FileField(upload_to='output/enhanced/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crime_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='ActionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_file', models.FileField(upload_to='output/action/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crime_app.video')),
            ],
        ),
    ]
