# Generated by Django 4.1.2 on 2023-10-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0002_rename_video_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
    ]
